version: 2.1
description: 'Test orb for prisma scan orb'

orbs:
  prisma: prisma_cloud/devops_security@2.2.0

workflows:
  scan:
    jobs:
      - prisma/iac_scan:
          prisma_cloud_api_url: https://api2.prismacloud.io    # Default env variable: PC_API_URL
          access_key: PC_ACCESS_KEY
          secret_key: PC_SECRET_KEY
          failure_criteria_high_severity: 1
          failure_criteria_medium_severity: 2
          failure_criteria_low_severity: 3
          failure_criteria_operator: and
          terraform_variable_filenames: variable.tf #comma separated list of variable file names
          tags: 'env:development, team:shiftleft'
